### ISSUE TITLE
Microservices applications do not work?

### ISSUE THREAD

**Issue by Arnaud-J** [abuijze/bike-rental-extended#1]
Hi Allard,

I am really interested in this application because I am trying to apply the monolith vs microservices approach for my application, which you implement in this one. Indeed, being able to run the application as a monolith (i.e. a single @SpringBootApplication, i.e. single JVM) for local development and/or as multiple microservices (i.e. multiple @SpringBootApplication, i.e. multiple JVMs) for remote environments is very interesting in terms of performance and modularity.

The problem is I can't make the microservices versions work. The Spring applications start normally, but no Axon event handler, command handler nor query handler is registered. Hence the application either stops normally (rental-query, rental-payment) or stays up but does nothing (rental-command, rental-ui).
The monolith application works and registers the handlers normally.

Here are the maven commands I used to start the services:
```bash
# microservices/rental-query
./mvnw spring-boot:run -pl microservices/rental-query

# microservices/rental-command
./mvnw spring-boot:run -pl microservices/rental-command

# microservices/rental-payment
./mvnw spring-boot:run -pl microservices/rental-payment

# microservices/rental-ui
./mvnw spring-boot:run -pl microservices/rental-ui
```

Also note that I have a standard version of Axon Server running at http://localhost:8124 and I can see in the application logs that they manage to connect successfully.

**Is there something I am missing in the way I run the applications ?**
Also, a README file would come handy to explain how to run this sample. Thanks!

**Comment by abuijze** [comment]
Hi Arnaud,

this repository wasn't really meant as a sample. It's an application I use in a demo. The "microservices" projects are empty. There is just a placeholder application class and a minuscule bit of configuration. The idea is that you can move the classes from the "monolith" to their respective microservices.

**Comment by Arnaud-J** [comment]
Ok I get it! In this case, does it even make sense to separate the classes of a single domain in their respective microservices? I feel like this would be hard to maintain: an upcaster, for example, might be needed in the command microservice and in any microservice having an @EventHandler for the targeted event. This would make us duplicate the upcaster class.

Aren't Spring profiles (only for Spring projects of course) a better alternative for a microservices approach? Allowing us to keep the code in one module/project, but still be able to run microservices as defined by the profiles.
